<?php
acf_add_local_field_group(array(
    'key'                           => 'group_page_5G9hFG9cgxnmHEHT',
    'title'                         => esc_attr__('Blog Post Options','teamhost'),
    'fields' => array(
        /*-------------------------------------------------------------------
        ==  Blog Setting
        -------------------------------------------------------------------*/
        array(
            'key'                   => 'field_XS5vnP8HHQGBF',
            'label'                 => '<span class="dashicons dashicons-grid-view"></span>'.esc_attr__('Blog Setting','teamhost'),
            'name'                  => '',
            'type'                  => 'tab',
            'instructions'          => '',
            'required'              => 0,
            'conditional_logic'     => 0,
            'wrapper' => array(
                'width'                             => '',
                'class'                             => '',
                'id'                                => '',
            ),
            'placement'             => 'left',
            'endpoint'              => 0,
        ),
        array(
            'key'                   => 'field_RSzSD1O0niiyA',
            'label'                 => esc_attr__('Post Style','teamhost'),
            'name'                  => 'blog_archive_style',
            'type'                  => 'select',
            'instructions'          => '',
            'required'              => 0,
            'conditional_logic'     => 0,
            'wrapper' => array(
                'width'                             => '',
                'class'                             => '',
                'id'                                => '',
            ),
            'choices' => array(
                'default'                       => esc_attr__('Default','teamhost'),
                'grid'                          => esc_attr__('Grid','teamhost'),
            ),
            'default_value' => 'default',
            'layout'                => 'vertical',
            'toggle'                => 0,
            'return_format'         => 'value',
        ),
        array(
            'key'                   => 'field_fUdpQeSH3x3WCym5',
            'label'                 => esc_attr__('Post per page','teamhost'),
            'name'                  => 'post_per_page',
            'type'                  => 'text',
            'instructions'          => '',
            'required'              => 0,
            'conditional_logic'     => 0,
            'wrapper' => array(
                'width'                                 => '',
                'class'                                 => '',
                'id'                                    => '',
            ),
            'choices'               => array(),
            'default_value'         => '9',
            'layout'                => 'vertical',
            'toggle'                => 0,
            'return_format'         => 'value',
        ),
        array(
            'key'                   => 'field_6CjgumMvyzb23cpage',
            'label'                 => esc_attr__('Blog Animation','teamhost'),
            'name'                  => 'blog_animation',
            'type'                  => 'select',
            'instructions'          => '',
            'required'              => 0,
            'conditional_logic'     => 0,
            'wrapper' => array(
                'width'                             => '',
                'class'                             => '',
                'id'                                => '',
            ),
            'choices' => array(
                'disable'                =>         esc_attr__('Disable','teamhost'),
                'fadeIn'                 =>         esc_attr__('fadeIn','teamhost'),
                'flipXIn'                =>         esc_attr__('flipXIn','teamhost'),
                'flipYIn'                =>         esc_attr__('flipYIn','teamhost'),
                'flipBounceXIn'          =>         esc_attr__('flipBounceXIn','teamhost'),
                'flipBounceYIn'          =>         esc_attr__('flipBounceYIn','teamhost'),
                'swoopIn'                =>         esc_attr__('swoopIn','teamhost'),
                'raise'                  =>         esc_attr__('raise','teamhost'),
                'whirlIn'                =>         esc_attr__('whirlIn','teamhost'),
                'shrinkIn'               =>         esc_attr__('shrinkIn','teamhost'),
                'expandIn'               =>         esc_attr__('expandIn','teamhost'),
                'bounceIn'               =>         esc_attr__('bounceIn','teamhost'),
                'bounceUpIn'             =>         esc_attr__('bounceUpIn','teamhost'),
                'bounceDownIn'           =>         esc_attr__('bounceDownIn','teamhost'),
                'bounceLeftIn'           =>         esc_attr__('bounceLeftIn','teamhost'),
                'bounceRightIn'          =>         esc_attr__('bounceRightIn','teamhost'),
                'slideUpIn'              =>         esc_attr__('slideUpIn','teamhost'),
                'slideDownIn'            =>         esc_attr__('slideDownIn','teamhost'),
                'slideLeftIn'            =>         esc_attr__('slideLeftIn','teamhost'),
                'slideRightIn'           =>         esc_attr__('slideRightIn','teamhost'),
                'slideUpBigIn'           =>         esc_attr__('slideUpBigIn','teamhost'),
                'slideDownBigIn'         =>         esc_attr__('slideDownBigIn','teamhost'),
                'slideLeftBigIn'         =>         esc_attr__('slideLeftBigIn','teamhost'),
                'slideRightBigIn'        =>         esc_attr__('slideRightBigIn','teamhost'),
                'perspectiveUpIn'        =>         esc_attr__('perspectiveUpIn','teamhost'),
                'perspectiveDownIn'      =>         esc_attr__('perspectiveDownIn','teamhost'),
                'perspectiveLeftIn'      =>         esc_attr__('perspectiveLeftIn','teamhost'),
                'perspectiveRightIn'     =>         esc_attr__('perspectiveRightIn','teamhost'),
                'zoomIn'                 =>         esc_attr__('zoomIn','teamhost'),
                'slideInRightVeryBig'    =>         esc_attr__('slideInRightVeryBig','teamhost'),
                'slideInLeftVeryBig'     =>         esc_attr__('slideInLeftVeryBig','teamhost'),
            ),
            'default_value'         => array(),
            'layout'                => 'vertical',
            'toggle'                => 0,
            'return_format'         => 'value',
        ),


        /*-------------------------------------------------------------------
         ==  Sidebar Setting
        -------------------------------------------------------------------*/
        array(
            'key'                   => 'field_ghYeEwwoh6Qeu',
            'label'                 => '<span class="dashicons dashicons-align-right"></span>'.esc_attr__('Sidebar Setting','teamhost'),
            'name'                  => '',
            'type'                  => 'tab',
            'instructions'          => '',
            'required'              => 0,
            'conditional_logic'     => 0,
            'wrapper' => array(
                'width'                             => '',
                'class'                             => '',
                'id'                                => '',
            ),
            'placement'             => 'left',
            'endpoint'              => 0,
        ),
        array(
            'key'                   => 'field_adF1VkIkBqala',
            'label'                 => esc_attr__('Sidebar','teamhost'),
            'name'                  => 'blog_template_sidebar',
            'type'                  => 'select',
            'instructions'          => '',
            'required'              => 0,
            'conditional_logic'     => 0,
            'wrapper' => array(
                'width'                             => '',
                'class'                             => '',
                'id'                                => '',
            ),
            'choices' => array(
                'disable'                   => esc_attr__('Disable','teamhost'),
                'left'                      => esc_attr__('Left','teamhost'),
                'right'                     => esc_attr__('Right','teamhost'),
            ),
            'default_value' => array(
                0                                   => 'right',
            ),
            'layout'                => 'vertical',
            'toggle'                => 0,
            'return_format'         => 'value',
        ),

    ),
    'location' => array(
        array(
            array(
                'param'                                 => 'page_template',
                'operator'                              => '==',
                'value'                                 => 'template-blog.php',
            ),
        ),
    ),
    'menu_order'                    => 0,
    'position'                      => 'normal',
    'style'                         => 'default',
    'label_placement'               => 'top',
    'instruction_placement'         => 'label',
    'hide_on_screen'                => '',
    'active'                        => 1,
    'description'                   => '',
));